//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v15.3.1+06a2a50
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "uToursSettingsComposition"
	/// <summary>[uTours] Settings Composition</summary>
	public partial interface IUToursSettingsComposition : IPublishedContent
	{
		/// <summary>Auto Scroll</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool AutoScroll { get; }

		/// <summary>Auto Scroll Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		int AutoScrollOffset { get; }

		/// <summary>Auto Scroll Smooth</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool AutoScrollSmooth { get; }

		/// <summary>Backdrop Animate</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool BackdropAnimate { get; }

		/// <summary>Backdrop Class</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BackdropClass { get; }

		/// <summary>Backdrop Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BackdropColor { get; }

		/// <summary>Show Close Button</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool CloseButton { get; }

		/// <summary>Complete on Finish</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool CompleteOnFinish { get; }

		/// <summary>Dialog Animate</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string DialogAnimate { get; }

		/// <summary>Dialog Class</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string DialogClass { get; }

		/// <summary>Dialog Max. Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		int DialogMaxWidth { get; }

		/// <summary>Dialog Placement</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string DialogPlacement { get; }

		/// <summary>Dialog Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		int DialogWidth { get; }

		/// <summary>Dialog Z</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		int DialogZ { get; }

		/// <summary>Exit On Click Outside</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool ExitOnClickOutside { get; }

		/// <summary>Exit on Escape</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool ExitOnEscape { get; }

		/// <summary>Finish Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FinishLabel { get; }

		/// <summary>Hide Back Button</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool HideBackButton { get; }

		/// <summary>Hide Next Button</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool HideNext { get; }

		/// <summary>Keyboard Controls</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool KeyboardControls { get; }

		/// <summary>Next Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NextLabel { get; }

		/// <summary>onAfterExit</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string OnAfterExit { get; }

		/// <summary>onAfterStepChange</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string OnAfterStepChange { get; }

		/// <summary>onBeforeExit</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string OnBeforeExit { get; }

		/// <summary>onBeforeStepChange</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string OnBeforeStepChange { get; }

		/// <summary>onFinish</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string OnFinish { get; }

		/// <summary>Prev. Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrevLabel { get; }

		/// <summary>Progress Bar</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ProgressBar { get; }

		/// <summary>Propagate Events</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool PropagateEvents { get; }

		/// <summary>Remember Step</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool RememberStep { get; }

		/// <summary>Show Buttons</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool ShowButtons { get; }

		/// <summary>Show Step Dots</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool ShowStepDots { get; }

		/// <summary>Show Step Progress</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		bool ShowStepProgress { get; }

		/// <summary>Step Dots Placement</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string StepDotsPlacement { get; }

		/// <summary>Target Padding</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		int TargetPadding { get; }
	}

	/// <summary>[uTours] Settings Composition</summary>
	[PublishedModel("uToursSettingsComposition")]
	public partial class UToursSettingsComposition : PublishedContentModel, IUToursSettingsComposition
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public new const string ModelTypeAlias = "uToursSettingsComposition";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<UToursSettingsComposition, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public UToursSettingsComposition(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Auto Scroll: Auto scroll browser window to the target element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("autoScroll")]
		public virtual bool AutoScroll => GetAutoScroll(this, _publishedValueFallback);

		/// <summary>Static getter for Auto Scroll</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetAutoScroll(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "autoScroll");

		///<summary>
		/// Auto Scroll Offset: When auto scrolling to an element, set the surrounding margin that should be scrolled into view. Defined in pixels.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("autoScrollOffset")]
		public virtual int AutoScrollOffset => GetAutoScrollOffset(this, _publishedValueFallback);

		/// <summary>Static getter for Auto Scroll Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static int GetAutoScrollOffset(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "autoScrollOffset");

		///<summary>
		/// Auto Scroll Smooth: Auto scroll browser window to the target element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("autoScrollSmooth")]
		public virtual bool AutoScrollSmooth => GetAutoScrollSmooth(this, _publishedValueFallback);

		/// <summary>Static getter for Auto Scroll Smooth</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetAutoScrollSmooth(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "autoScrollSmooth");

		///<summary>
		/// Backdrop Animate: Apply CSS transition class on backdrop to enable smooth resizing and repositioning on step change.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("backdropAnimate")]
		public virtual bool BackdropAnimate => GetBackdropAnimate(this, _publishedValueFallback);

		/// <summary>Static getter for Backdrop Animate</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetBackdropAnimate(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "backdropAnimate");

		///<summary>
		/// Backdrop Class: Add a custom CSS class to the backdrop element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backdropClass")]
		public virtual string BackdropClass => GetBackdropClass(this, _publishedValueFallback);

		/// <summary>Static getter for Backdrop Class</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBackdropClass(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "backdropClass");

		///<summary>
		/// Backdrop Color: Use a custom color for the tour backdrop.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backdropColor")]
		public virtual string BackdropColor => GetBackdropColor(this, _publishedValueFallback);

		/// <summary>Static getter for Backdrop Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBackdropColor(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "backdropColor");

		///<summary>
		/// Show Close Button: Display the close button in the top-right corner of the tour dialog.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("closeButton")]
		public virtual bool CloseButton => GetCloseButton(this, _publishedValueFallback);

		/// <summary>Static getter for Show Close Button</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetCloseButton(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "closeButton");

		///<summary>
		/// Complete on Finish: Use TourGuide JS' in-built handler for detecting when a user has completed a tour using localStorage.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("completeOnFinish")]
		public virtual bool CompleteOnFinish => GetCompleteOnFinish(this, _publishedValueFallback);

		/// <summary>Static getter for Complete on Finish</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetCompleteOnFinish(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "completeOnFinish");

		///<summary>
		/// Dialog Animate: Apply CSS transition class on the tour guide element to enable smooth resizing and repositioning on step change.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dialogAnimate")]
		public virtual string DialogAnimate => GetDialogAnimate(this, _publishedValueFallback);

		/// <summary>Static getter for Dialog Animate</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetDialogAnimate(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "dialogAnimate");

		///<summary>
		/// Dialog Class: Add a custom CSS class to the tour dialog element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dialogClass")]
		public virtual string DialogClass => GetDialogClass(this, _publishedValueFallback);

		/// <summary>Static getter for Dialog Class</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetDialogClass(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "dialogClass");

		///<summary>
		/// Dialog Max. Width: Maximum width for the tour guide dialog.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("dialogMaxWidth")]
		public virtual int DialogMaxWidth => GetDialogMaxWidth(this, _publishedValueFallback);

		/// <summary>Static getter for Dialog Max. Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static int GetDialogMaxWidth(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "dialogMaxWidth");

		///<summary>
		/// Dialog Placement: Floating ui placement for the tour guide dialog.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dialogPlacement")]
		public virtual string DialogPlacement => GetDialogPlacement(this, _publishedValueFallback);

		/// <summary>Static getter for Dialog Placement</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetDialogPlacement(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "dialogPlacement");

		///<summary>
		/// Dialog Width: Set a strict width for the dialog in px. Recommended if loading images in the content to maintain precise positioning.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("dialogWidth")]
		public virtual int DialogWidth => GetDialogWidth(this, _publishedValueFallback);

		/// <summary>Static getter for Dialog Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static int GetDialogWidth(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "dialogWidth");

		///<summary>
		/// Dialog Z: CSS z-index property of the tour dialog element. Defaults to 999.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("dialogZ")]
		public virtual int DialogZ => GetDialogZ(this, _publishedValueFallback);

		/// <summary>Static getter for Dialog Z</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static int GetDialogZ(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "dialogZ");

		///<summary>
		/// Exit On Click Outside: Exit the tour on when a user clicks outside the tour.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("exitOnClickOutside")]
		public virtual bool ExitOnClickOutside => GetExitOnClickOutside(this, _publishedValueFallback);

		/// <summary>Static getter for Exit On Click Outside</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetExitOnClickOutside(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "exitOnClickOutside");

		///<summary>
		/// Exit on Escape: Exit the tour on escape key press. Can be used in conjunction with keyboardControls.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("exitOnEscape")]
		public virtual bool ExitOnEscape => GetExitOnEscape(this, _publishedValueFallback);

		/// <summary>Static getter for Exit on Escape</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetExitOnEscape(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "exitOnEscape");

		///<summary>
		/// Finish Label: Caption for the finish button displayed on the last tour guide step. If empty, defaults to 'Finish'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("finishLabel")]
		public virtual string FinishLabel => GetFinishLabel(this, _publishedValueFallback);

		/// <summary>Static getter for Finish Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFinishLabel(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "finishLabel");

		///<summary>
		/// Hide Back Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("hideBackButton")]
		public virtual bool HideBackButton => GetHideBackButton(this, _publishedValueFallback);

		/// <summary>Static getter for Hide Back Button</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetHideBackButton(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "hideBackButton");

		///<summary>
		/// Hide Next Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("hideNext")]
		public virtual bool HideNext => GetHideNext(this, _publishedValueFallback);

		/// <summary>Static getter for Hide Next Button</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetHideNext(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "hideNext");

		///<summary>
		/// Keyboard Controls: Support keyboard controls for forwards & backwards arrows as well as escape key.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("keyboardControls")]
		public virtual bool KeyboardControls => GetKeyboardControls(this, _publishedValueFallback);

		/// <summary>Static getter for Keyboard Controls</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetKeyboardControls(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "keyboardControls");

		///<summary>
		/// Next Label: Caption for the next button. If empty, defaults to 'Next'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nextLabel")]
		public virtual string NextLabel => GetNextLabel(this, _publishedValueFallback);

		/// <summary>Static getter for Next Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNextLabel(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nextLabel");

		///<summary>
		/// onAfterExit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onAfterExit")]
		public virtual string OnAfterExit => GetOnAfterExit(this, _publishedValueFallback);

		/// <summary>Static getter for onAfterExit</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetOnAfterExit(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "onAfterExit");

		///<summary>
		/// onAfterStepChange
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onAfterStepChange")]
		public virtual string OnAfterStepChange => GetOnAfterStepChange(this, _publishedValueFallback);

		/// <summary>Static getter for onAfterStepChange</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetOnAfterStepChange(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "onAfterStepChange");

		///<summary>
		/// onBeforeExit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onBeforeExit")]
		public virtual string OnBeforeExit => GetOnBeforeExit(this, _publishedValueFallback);

		/// <summary>Static getter for onBeforeExit</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetOnBeforeExit(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "onBeforeExit");

		///<summary>
		/// onBeforeStepChange
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onBeforeStepChange")]
		public virtual string OnBeforeStepChange => GetOnBeforeStepChange(this, _publishedValueFallback);

		/// <summary>Static getter for onBeforeStepChange</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetOnBeforeStepChange(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "onBeforeStepChange");

		///<summary>
		/// onFinish
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("onFinish")]
		public virtual string OnFinish => GetOnFinish(this, _publishedValueFallback);

		/// <summary>Static getter for onFinish</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetOnFinish(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "onFinish");

		///<summary>
		/// Prev. Label: Caption for the back button. If empty, defaults to 'Prev'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("prevLabel")]
		public virtual string PrevLabel => GetPrevLabel(this, _publishedValueFallback);

		/// <summary>Static getter for Prev. Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrevLabel(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "prevLabel");

		///<summary>
		/// Progress Bar: Show progress bar under dialog header - pass a colour string to enable
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("progressBar")]
		public virtual string ProgressBar => GetProgressBar(this, _publishedValueFallback);

		/// <summary>Static getter for Progress Bar</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetProgressBar(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "progressBar");

		///<summary>
		/// Propagate Events: Allow the user to click elements within the target highlight area.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("propagateEvents")]
		public virtual bool PropagateEvents => GetPropagateEvents(this, _publishedValueFallback);

		/// <summary>Static getter for Propagate Events</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetPropagateEvents(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "propagateEvents");

		///<summary>
		/// Remember Step: Continue the tour from last active step when re-opening.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("rememberStep")]
		public virtual bool RememberStep => GetRememberStep(this, _publishedValueFallback);

		/// <summary>Static getter for Remember Step</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetRememberStep(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "rememberStep");

		///<summary>
		/// Show Buttons: Display the next and prev buttons. Can be used in conjunction with hideNext & hidePrev.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("showButtons")]
		public virtual bool ShowButtons => GetShowButtons(this, _publishedValueFallback);

		/// <summary>Static getter for Show Buttons</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetShowButtons(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "showButtons");

		///<summary>
		/// Show Step Dots: Show the tour progress marker dots.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("showStepDots")]
		public virtual bool ShowStepDots => GetShowStepDots(this, _publishedValueFallback);

		/// <summary>Static getter for Show Step Dots</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetShowStepDots(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "showStepDots");

		///<summary>
		/// Show Step Progress: Show `1/5` human-readable step progress in the tour dialog footer.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("showStepProgress")]
		public virtual bool ShowStepProgress => GetShowStepProgress(this, _publishedValueFallback);

		/// <summary>Static getter for Show Step Progress</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static bool GetShowStepProgress(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "showStepProgress");

		///<summary>
		/// Step Dots Placement: Whether to output the step dots in the tour dialog body or centered in the footer. Defaults to 'footer'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("stepDotsPlacement")]
		public virtual string StepDotsPlacement => GetStepDotsPlacement(this, _publishedValueFallback);

		/// <summary>Static getter for Step Dots Placement</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetStepDotsPlacement(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "stepDotsPlacement");

		///<summary>
		/// Target Padding: The space around the highlighted step element in pixels.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		[ImplementPropertyType("targetPadding")]
		public virtual int TargetPadding => GetTargetPadding(this, _publishedValueFallback);

		/// <summary>Static getter for Target Padding</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.1+06a2a50")]
		public static int GetTargetPadding(IUToursSettingsComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "targetPadding");
	}
}
